/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/oCNVEiCZ1f4
 */
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { CardHeader, CardContent, Card } from "@/components/ui/card"

export function Landing() {
  return (
    <div className="flex flex-col min-h-screen">
      <header className="px-4 lg:px-6 h-14 flex items-center">
        <Link className="flex items-center justify-center" href="#">
          <FacebookIcon className="h-6 w-6" />
          <span className="sr-only">Fintech Inc</span>
        </Link>
        <nav className="ml-auto flex gap-4 sm:gap-6">
          <Link className="text-sm font-medium hover:underline underline-offset-4" href="#">
            Services
          </Link>
          <Link className="text-sm font-medium hover:underline underline-offset-4" href="#">
            Pricing
          </Link>
          <Link className="text-sm font-medium hover:underline underline-offset-4" href="#">
            About Us
          </Link>
        </nav>
      </header>
      <main className="flex-1">
        <section className="bg-gray-100 dark:bg-gray-800 py-12 md:py-24 lg:py-32">
          <div className="container px-4 md:px-6">
            <div className="grid gap-6 lg:grid-cols-2 lg:gap-12">
              <div className="flex flex-col justify-center space-y-4">
                <h1 className="text-4xl font-bold tracking-tighter sm:text-5xl xl:text-6xl">
                  Simplifying Financial Management
                </h1>
                <p className="max-w-[600px] text-gray-500 md:text-xl dark:text-gray-400">
                  At Fintech Inc, we provide innovative solutions to manage your finances effectively and efficiently.
                </p>
                <Button>Get Started</Button>
              </div>
              <FacebookIcon className="mx-auto h-64 w-64 lg:order-last" />
            </div>
          </div>
        </section>
        <section className="py-12 md:py-24 lg:py-32">
          <div className="container px-4 md:px-6">
            <h2 className="text-3xl font-semibold text-center mb-10">Our Services</h2>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
              <Card>
                <CardHeader>
                  <h3 className="text-lg font-semibold">Personal Finance</h3>
                </CardHeader>
                <CardContent>
                  <p className="text-gray-500">
                    Manage your personal finances with our easy-to-use tools and features.
                  </p>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <h3 className="text-lg font-semibold">Business Solutions</h3>
                </CardHeader>
                <CardContent>
                  <p className="text-gray-500">We provide comprehensive financial solutions for your business needs.</p>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <h3 className="text-lg font-semibold">Investment Planning</h3>
                </CardHeader>
                <CardContent>
                  <p className="text-gray-500">Get advice on investment strategies from our experienced advisors.</p>
                </CardContent>
              </Card>
            </div>
          </div>
        </section>
        <section className="py-12 md:py-24 lg:py-32">
          <div className="container px-4 md:px-6">
            <h2 className="text-3xl font-semibold text-center mb-10">Price Plans</h2>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
              <Card>
                <CardHeader>
                  <h3 className="text-lg font-semibold">Basic</h3>
                  <p className="text-lg font-semibold mt-2">$9.99 / month</p>
                </CardHeader>
                <CardContent>
                  <p className="text-gray-500">Ideal for beginners. Get access to basic features and tools.</p>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <h3 className="text-lg font-semibold">Standard</h3>
                  <p className="text-lg font-semibold mt-2">$19.99 / month</p>
                </CardHeader>
                <CardContent>
                  <p className="text-gray-500">Perfect for regular users. Enjoy additional features and benefits.</p>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <h3 className="text-lg font-semibold">Premium</h3>
                  <p className="text-lg font-semibold mt-2">$29.99 / month</p>
                </CardHeader>
                <CardContent>
                  <p className="text-gray-500">Best for heavy users. Take full advantage of our platform.</p>
                </CardContent>
              </Card>
              <Card className="bg-blue-500 text-white">
                <CardHeader>
                  <h3 className="text-lg font-semibold">Enterprise</h3>
                  <p className="text-lg font-semibold mt-2">Contact us for pricing</p>
                </CardHeader>
                <CardContent>
                  <p className="text-gray-200">Tailored solutions for your business. Contact us for more info.</p>
                </CardContent>
              </Card>
            </div>
          </div>
        </section>
      </main>
      <footer className="px-4 py-6 border-t">
        <div className="container flex items-center justify-between">
          <div className="text-sm text-gray-500">© Fintech Inc.</div>
          <nav>
            <Link className="text-sm text-gray-500 hover:underline" href="#">
              Terms of Service
            </Link>
            <Link className="ml-4 text-sm text-gray-500 hover:underline" href="#">
              Privacy Policy
            </Link>
          </nav>
        </div>
      </footer>
    </div>
  )
}


function FacebookIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z" />
    </svg>
  )
}
