/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/oCNVEiCZ1f4
 */
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { CardHeader, CardContent, Card } from "@/components/ui/card";

export function Landing() {
  return (
    <div className="flex flex-col min-h-screen">
      <header className="px-4 lg:px-6 h-14 flex items-center">
        <Link className="flex items-center justify-center" href="/">
          <AppIcon className="h-6 w-6" />
          <span className="sr-only">نرم افزار ابری وزیر</span>
        </Link>
        <nav className="ml-auto flex gap-4 sm:gap-6">
          <Link
            className="text-sm font-medium hover:underline underline-offset-4"
            href="#"
          >
            خدمات
          </Link>
          <Link
            className="text-sm font-medium hover:underline underline-offset-4"
            href="#"
          >
            قیمت ها
          </Link>
          <Link
            className="text-sm font-medium hover:underline underline-offset-4"
            href="#"
          >
            درباره ما
          </Link>
        </nav>
      </header>
      <main className="flex-1">
        <section className="bg-gray-100 dark:bg-gray-800 py-12 md:py-24 lg:py-32">
          <div className="container px-4 md:px-6">
            <div className="grid gap-6 lg:grid-cols-2 lg:gap-12">
              <div className="flex flex-col justify-center space-y-4">
                <h1 className="text-4xl font-bold tracking-tighter sm:text-5xl xl:text-6xl">
                  ساده سازی مدیریت مالی
                </h1>
                <p className="max-w-[600px] text-gray-500 md:text-xl dark:text-gray-400">
                  ما در پلتفرم وزیر راه حل های نوآورانه ای برای مدیریت شما ارائه
                  می دهیم که به طور موثر و کارآمد می کند
                </p>
                <Button>شروع کنید</Button>
              </div>
              <AppIcon className="mx-auto h-64 w-64 lg:order-last" />
            </div>
          </div>
        </section>
        <section className="py-12 md:py-24 lg:py-32">
          <div className="container px-4 md:px-6">
            <h2 className="text-3xl font-semibold text-center mb-10">
              خدمات ما
            </h2>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
              <Card>
                <CardHeader>
                  <h3 className="text-lg font-semibold">مدیریت مالی</h3>
                </CardHeader>
                <CardContent>
                  <p className="text-gray-500">
                    امور مالی خود را با ابزارهای ساده و امکانات کاربردی ما
                    مدیریت کنید
                  </p>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <h3 className="text-lg font-semibold">
                    راه حل های کسب و کار
                  </h3>
                </CardHeader>
                <CardContent>
                  <p className="text-gray-500">
                    ما راه حل های مالی جامعی را برای نیاز های تجاری شما ارائه می
                    دهیم
                  </p>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <h3 className="text-lg font-semibold">
                    برنامه ریزی جامع مالی
                  </h3>
                </CardHeader>
                <CardContent>
                  <p className="text-gray-500">
                    در مورد استراتژی های سرمایه گذاری از مشاوران مجرب ما مشاوره
                    بگیرید
                  </p>
                </CardContent>
              </Card>
            </div>
          </div>
        </section>
        <section className="py-12 md:py-24 lg:py-32">
          <div className="container px-4 md:px-6">
            <h2 className="text-3xl font-semibold text-center mb-10">طرح ها</h2>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
              <Card>
                <CardHeader>
                  <h3 className="text-lg font-semibold">پایه</h3>
                  <p className="text-lg font-semibold mt-2">$ماه / بزودی</p>
                </CardHeader>
                <CardContent>
                  <p className="text-gray-500">
                    ایده آل برای مبتدیان، به ویژگی ها و ابزارهای اساسی دسترسی
                    پیدا کنید
                  </p>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <h3 className="text-lg font-semibold">استاندارد</h3>
                  <p className="text-lg font-semibold mt-2">$ماه / بزودی</p>
                </CardHeader>
                <CardContent>
                  <p className="text-gray-500">
                    ایده آل برای کاربران عادی، شامل ویژگی های جدید و پیشرفته
                  </p>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <h3 className="text-lg font-semibold">پیشرفته</h3>
                  <p className="text-lg font-semibold mt-2">$ماه / بزودی</p>
                </CardHeader>
                <CardContent>
                  <p className="text-gray-500">
                    بهترین برای کاربران سنگین، از پلتفرم ما نهایت استفاده را
                    ببرید
                  </p>
                </CardContent>
              </Card>
              <Card className="bg-blue-500 text-white">
                <CardHeader>
                  <h3 className="text-lg font-semibold">جامع</h3>
                  <p className="text-lg font-semibold mt-2">
                    با ما تماس بگیرید
                  </p>
                </CardHeader>
                <CardContent>
                  <p className="text-gray-200">
                    راه حل های مناسب برای کسب و کار شما، برای اطلاعات بیشتر با
                    ما تماس بگیرید
                  </p>
                </CardContent>
              </Card>
            </div>
          </div>
        </section>
      </main>
      <footer className="px-4 py-6 border-t">
        <div className="container flex items-center justify-between">
          <div className="text-sm text-gray-500">© Vazir Inc.</div>
          <nav>
            <Link className="text-sm text-gray-500 hover:underline" href="#">
              شرایط استفاده از خدمات
            </Link>
            <hr />
            <Link
              className="ml-4 text-sm text-gray-500 hover:underline"
              href="#"
            >
              سیاست حفظ حریم خصوصی
            </Link>
          </nav>
        </div>
      </footer>
    </div>
  );
}

function AppIcon(props: any) {
  return (
    // <svg
    // {...props}
    //   xmlns="http://www.w3.org/2000/svg"
    //   width="24"
    //   height="24"
    //   viewBox="0 0 24 24"
    //   fill="none"
    //   stroke="currentColor"
    //   strokeWidth="2"
    //   strokeLinecap="round"
    //   strokeLinejoin="round"
    // >
    //   <path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z" />
    // </svg>

    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="490.000000pt"
      height="433.000000pt"
      viewBox="0 0 490.000000 433.000000"
      preserveAspectRatio="xMidYMid meet"
    >
      <g
        transform="translate(0.000000,433.000000) scale(0.100000,-0.100000)"
        fill="#000000"
        stroke="none"
      >
        <path
          d="M3442 3920 c-262 -69 -479 -290 -542 -551 -115 -480 244 -939 735
-939 299 0 587 194 699 469 127 315 29 686 -235 886 -77 58 -200 117 -290 139
-92 23 -272 21 -367 -4z"
        />
        <path
          d="M15 3836 c-12 -8 -16 -19 -11 -31 6 -16 72 -123 336 -550 48 -77 183
-295 300 -485 117 -190 263 -426 325 -525 62 -99 248 -400 415 -670 166 -269
368 -596 448 -725 80 -129 197 -318 260 -420 288 -464 267 -435 297 -428 17 3
704 1103 705 1127 0 12 -81 146 -505 831 -56 91 -194 314 -305 495 -112 182
-224 364 -250 405 -26 41 -73 118 -105 170 -32 52 -86 140 -120 195 -34 55
-129 208 -210 340 -82 132 -157 250 -168 263 l-20 22 -687 0 c-562 0 -690 -2
-705 -14z"
        />
      </g>
    </svg>
  );
}
