name: Build Vue
on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
      - uses: actions/checkout@v2
      - id: Build-Vue
        uses: xRealNeon/VuePagesAction@1.0.1
        with:
          username: 'aminwhat'
          reponame: 'vazir.io.github.io'
          token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
          gitemail: 'm.aminwhat@gmail.com'
          cname: 'vazir.io'
